###
# This workflow is used for quickly building artifacts
# Triggers:
#   1. Manual trigger
# Jobs:
#   1. Calculate Version Number
#   2. Build Web Artifact
#   3. Build Client Artifact
###

name: Build Airflow
run-name: Build Airflow triggered by ${{ github.actor }} 🛠️

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-web-x86_64:
    name: Build Web Artifact (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
      - name: Build docker image (x86_64)
        run: |
          docker pull apache/airflow:2.9.3-python3.9
          docker save -o airflow.tar.gz apache/airflow:2.9.3-python3.9
      - name: Upload docker image (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: airflow.tar.gz
          path: airflow.tar.gz