###
# This workflow is used for quickly building artifacts
# Triggers:
#   1. Manual trigger
# Jobs:
#   1. Calculate Version Number
#   2. Build Web Artifact
#   3. Build Client Artifact
###

name: Build Artifact
run-name: Build Artifact triggered by ${{ github.actor }} 🛠️

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-web-x86_64:
    name: Build Web Artifact (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
      - name: Build docker image (x86_64)
        run: |
          docker build -t docker.io/oceanbase/compute:0.0.4 -f distribution/Dockerfile .
          docker save -o obcloud-compute.tar.gz docker.io/oceanbase/compute:0.0.4
      - name: Upload docker image (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: obcloud-compute.tar.gz
          path: obcloud-compute.tar.gz